
- testcase:
      name: hw_config_name
      id: 1
      description: >
          This test is to set a component name.
      rpcs:
          - template: hw_config_name.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   name: "VOTA_TEST"
